language: go

addons:
  ssh_known_hosts: beevee.ru

go:
- 1.7

before_install:
- go get github.com/mattn/goveralls
- go get github.com/kardianos/govendor
- govendor sync

script:
- goveralls
- pushd cmd/switchersbot && go build && popd

before_deploy:
- openssl aes-256-cbc -K $encrypted_d08fb8755470_key -iv $encrypted_d08fb8755470_iv
  -in $TRAVIS_BUILD_DIR/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script:
  - rsync --quiet $TRAVIS_BUILD_DIR/cmd/switchersbot/switchersbot deploy@beevee.ru:/opt/switchersbot/
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script:
  - rsync --quiet $TRAVIS_BUILD_DIR/cmd/switchersbot/schedule.yml deploy@beevee.ru:/opt/switchersbot/
  on:
    branch: master
- provider: script
  script:
  - ssh deploy@beevee.ru 'sudo systemctl restart switchersbot'
  on:
    branch: master
